### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by tilltmk** [tilltmk/automated-documentation#1]
- [x] URL Capture via PyAutoGUI
- [x] Make Ollama Optional
- [x] Release for Linux
- [x] Optimize Markdown Output

**Comment by tilltmk** [comment]
also, 
- [x] archive every visited website
